Repository istio/pkg, pull requests merged in 2019-07, with the labels that each got.

#29 Initial checkin of the code coverage topic.
  .codecov.yml
  cover/assets/assets.gen.go
  cover/assets/assets.go
  cover/assets/templates/index.html
  cover/block.go
  cover/blockstate.go
  cover/coverage.go
  cover/ctrlz.go
  cover/ctrlz_test.go
  cover/doc.go
  cover/fns.go
  cover/registry.go
  cover/registry_test.go
Labels: cla: yes

#30 For istioctl version --short, coalese control plane version output
  version/cobra.go
  version/cobra_test.go
Labels: cla: yes

#31 feat(monitoring pkg): add new common monitoring package
  collateral/metrics/opencensus_test.go
  monitoring/doc.go
  monitoring/example_distribution_test.go
  monitoring/example_gauge_test.go
  monitoring/example_sum_test.go
  monitoring/monitoring.go
  monitoring/monitoring_test.go
  monitoring/units.go
Labels: cla: yes

#32 fix(monitoring): prevent empty labels in view
  monitoring/monitoring.go
  monitoring/monitoring_test.go
Labels: cla: yes

#33 [monitoring] Add decrement method
  monitoring/monitoring.go
  monitoring/monitoring_test.go
Labels: cla: yes

#37 README update.
  README.md
Labels: cla: yes, size/XS

#40 Fix a comment.
  pool/buffer.go
Labels: cla: yes, size/XS

#39 Disable mergify and CircleCi
  .circleci/config.yml
  .commonfiles.sha
  .mergify.yml
  Makefile
  README.md
  cover/assets/assets.go
  ctrlz/assets/assets.go
  ctrlz/topics/assets/assets.go
  scripts/check_dockerfiles.sh
  scripts/run_gobindata.sh
Labels: cla: yes, size/L

#41 Remove the now superfluous annotation doc code.
  collateral/control.go
Labels: cla: yes, size/M

#42 Retire now superfluous pkg/annotations.
  annotations/annotation.go
  annotations/annotation_test.go
Labels: cla: yes, size/L

#43 Trivial doc update to test out auto cherry picking.
  README.md
Labels: cherrypick/release-1.2, cla: yes, size/XS

#45 Add viper cmd functionality and test.
  go.mod
  go.sum
  viperconfig/testconfig.yaml
  viperconfig/viperconfig.go
  viperconfig/viperconfig_test.go
Labels: cla: yes, size/L

#47 fix(tests): attempt to deflake monitoring related flakes
  collateral/metrics/opencensus.go
  collateral/metrics/opencensus_test.go
  monitoring/monitoring_test.go
Labels: cla: yes, size/L
