Repository istio/pkg, pull requests merged in 2019-09, with the labels that each got.

#62 Add a build target and update the test target.
  Makefile.core.mk
Labels: cla: yes, size/XS

#64 Add predicate support to the collateral package.
  collateral/cobra.go
  collateral/control.go
  collateral/predicate.go
Labels: cla: yes, size/M

#63 Reimplement FileWatcher without races.
  filewatcher/fakefilewatcher.go
  filewatcher/filewatcher.go
  filewatcher/filewatcher_test.go
  filewatcher/out.txt
  filewatcher/worker.go
Labels: cla: yes, size/XL

#65 Fix deadlock problems in file watcher.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
  filewatcher/filewatcher.go
  filewatcher/filewatcher_test.go
  filewatcher/out.txt
  filewatcher/worker.go
Labels: cla: yes, size/L

#66 Another attempt at fixing some deadlocks.
  filewatcher/filewatcher.go
  filewatcher/filewatcher_test.go
  filewatcher/worker.go
Labels: cla: yes, size/L

#68 Update common files.
  .gitattributes
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  cover/ctrlz_test.go
  version/cobra.go
Labels: cla: yes, size/L

#67 Update Viperize to use new List Semantics from pflags.
  go.mod
  go.sum
  viperconfig/testconfig.yaml
  viperconfig/testlistconfig.yaml
  viperconfig/viperconfig.go
  viperconfig/viperconfig_test.go
Labels: cla: yes, size/M

#70 Update common files.
  Makefile
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/M

#71 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/gobuild.sh
  go.mod
  go.sum
Labels: cla: yes, size/L
