Repository istio/pkg, pull requests merged in 2019-08, with the labels that each got.

#48 Add Viperize for brevity
  viperconfig/testsubconfig.yaml
  viperconfig/viperconfig.go
  viperconfig/viperconfig_test.go
Labels: cla: yes, size/M

#50 Remove -c shorthand from viperize
  viperconfig/viperconfig.go
Labels: cla: yes, size/XS

#51 Handle arrays as well as slices in config processor
  viperconfig/viperconfig.go
Labels: cla: yes, size/XS

#52 Update common files.
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  scripts/run_gobindata.sh
Labels: cla: yes, size/M

#53 Add failing test for flag duplication
  viperconfig/viperconfig_test.go
Labels: cla: yes, size/S

#54 Set release managers as CODEOWNERS for release-1.3
  CODEOWNERS
Labels: area/test and release, cla: yes, size/XS

#55 try to save coverage file into ARTIFACTS
  Makefile.core.mk
Labels: cla: yes, size/XS

#58 Update common files.
  .commonfiles.sha
  Makefile
  Makefile.core.mk
Labels: cla: yes, size/XS

#59 Update common files
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/report_build_info.sh
  scripts/check_dockerfiles.sh
  scripts/lint_copyright_banner.sh
  scripts/run_gobindata.sh
  scripts/run_gofmt.sh
Labels: cla: yes, size/L

#60 Remove Host, User, and Hub from version string
  version/cobra_test.go
  version/version.go
  version/version_linux_test.go
  version/version_test.go
Labels: cla: yes, size/M

#61 Update common files.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
Labels: cla: yes, size/L
