Repository istio/pkg, pull requests merged in 2019-10, with the labels that each got.

#72 Dataplane versions
  version/cobra.go
  version/version.go
Labels: cla: yes, size/M

#74 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#73 Build Config Ledger for tracking pilot states
  go.mod
  go.sum
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/smt.go
  ledger/smt_test.go
  ledger/smt_tools.go
  ledger/trie_cache.go
  ledger/util.go
Labels: cla: yes, size/XXL

#76 Combing using Version instead of GitTag
  version/cobra.go
Labels: cla: yes, size/XS

#78 make ledger handle long keys better
  ledger/ledger.go
  ledger/ledger_test.go
Labels: cla: yes, size/M

#80 Release 1.4 codeowners
  CODEOWNERS
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/S

#75 Fix cache segfaults due to unaligned atomics on 32b architectures
  cache/lruCache.go
  cache/ttlCache.go
Labels: cla: yes, ok-to-test, size/XS

#81 Introduce DockerInfo with hub and tag values
  version/version.go
Labels: cla: yes, size/S

#86 Update the gen and gen-check targets to match expected semantics.
  Makefile.core.mk
Labels: cla: yes, size/XS

#84 Improve HTML collateral output.
  collateral/control.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#87 [release-1.4] Improve HTML collateral output.
  collateral/control.go
Labels: cla: yes, size/XS

#88 Improve rendering of the TOC for generated command docs.
  collateral/control.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#89 [release-1.4] Improve rendering of the TOC for generated command docs.
  collateral/control.go
Labels: cla: yes, size/XS

#83 [release-1.4] add DockerInfo with hub and tag variables
  version/version.go
Labels: cla: yes, size/S
