Repository istio/pkg, pull requests merged in 2020-05, with the labels that each got.

#152 Protect ledger root from race conditions
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/pkg.iml
  .idea/vcs.xml
  go.mod
  go.sum
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/smt.go
  ledger/smt_tools.go
  licenses/golang.org/x/mod/LICENSE
  licenses/golang.org/x/tools/third_party/moduleloader/LICENSE
  licenses/golang.org/x/tools/third_party/typescript/LICENSE
  licenses/golang.org/x/xerrors/LICENSE
Labels: cla: yes, size/L

#151 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#153 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#154 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#155 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#156 Automator: update common-files@release-1.6 in istio/pkg@release-1.6
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#157 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#158 Automator: update common-files@release-1.6 in istio/pkg@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#159 Automator: update common-files@release-1.5 in istio/pkg@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#160 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#161 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#162 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#163 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
