Repository istio/pkg, pull requests merged in 2020-03, with the labels that each got.

#115 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#116 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#117 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#118 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#119 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#121 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#122 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#123 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#124 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#125 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#126 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#120 Fix istioctl controlz dashboard UI shows error message in subpage
  ctrlz/topics/assets/assets.gen.go
  ctrlz/topics/assets/templates/proc.html
  ctrlz/topics/assets/templates/version.html
Labels: cla: yes, size/S

#128 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#129 Automator: update common-files@release-1.5 in istio/pkg@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#130 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#131 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S
