Repository istio/pkg, pull requests merged in 2020-09, with the labels that each got.

#219 Refactor log functions to use Scope logging methods
  log/config_test.go
  log/default.go
  log/default_test.go
Labels: cla: yes, size/L

#221 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#222 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#223 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#224 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#225 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#226 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#227 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#228 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#229 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#230 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#231 Pipe klog/v2 output through standard logging
  go.mod
  go.sum
  licenses/github.com/go-logr/logr/LICENSE
  licenses/k8s.io/klog/v2/LICENSE
  log/config.go
  log/logr.go
  log/logr_test.go
Labels: cla: yes, size/XL

#232 Do not panic on nil error for klog shim
  log/logr.go
Labels: cla: yes, size/XS

#233 Fix newlines for klog
  log/logr.go
  log/logr_test.go
Labels: cla: yes, size/S

#235 Add WithLabels to default scope
  log/default.go
  log/default_test.go
Labels: cla: yes, size/S

#236 Add support for wrapping structured.Error with %w
  log/default_test.go
  log/scope_test.go
  log/zapcore_handler.go
  structured/structured.go
Labels: cla: yes, size/M

#234 Fix zapcore field handling
  log/scope.go
  log/scope_test.go
  log/zapcore_handler.go
Labels: cla: yes, size/L

#237 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#238 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#240 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#241 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
