Repository istio/pkg, pull requests merged in 2020-06, with the labels that each got.

#164 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#165 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#166 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#167 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#168 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#169 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#170 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/M

#171 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#173 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#172 Sort scopes for controlz
  ctrlz/topics/scopes.go
Labels: cla: yes, size/XS

#174 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#175 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/XS

#176 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#177 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
