Repository istio/pkg, pull requests merged in 2020-07, with the labels that each got.

#178 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#179 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#180 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#181 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#182 Automator: update common-files@release-1.6 in istio/pkg@release-1.6
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#183 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#184 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#185 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#186 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#187 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#188 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/S

#189 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#190 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#191 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#194 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#193 Disable gRPC log by default
  log/config_test.go
  log/options.go
  log/options_test.go
Labels: cla: yes, size/S

#195 Set release managers as CODEOWNERS for release-1.7
  CODEOWNERS
Labels: cla: yes, size/XS

#192 Error dictionary and structured logging
  go.sum
  log/config.go
  log/scope.go
  log/scope_test.go
  log/zapcore_handler.go
  structured/structured.go
Labels: cherrypick/release-1.7, cla: yes, size/XL

#196 update common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#198 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#199 Automator: update common-files@release-1.7 in istio/pkg@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#200 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#197 [release-1.7] Error dictionary and structured logging
  go.sum
  log/config.go
  log/scope.go
  log/scope_test.go
  log/zapcore_handler.go
  structured/structured.go
Labels: cla: yes, size/XL

#201 Explicit lock to fix racetest
  log/scope.go
Labels: cherrypick/release-1.7, cla: yes

#202 [release-1.7] Explicit lock to fix racetest
  log/scope.go
Labels: cla: yes, release-notes-none, size/S

#203 Fix race in global var
  log/config.go
  log/zapcore_handler.go
Labels: cherrypick/release-1.7, cla: yes, size/XS

#204 [release-1.7] Fix race in global var
  log/config.go
  log/zapcore_handler.go
Labels: cla: yes, release-notes-none, size/XS

#205 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
