Repository istio/pkg, pull requests merged in 2020-01, with the labels that each got.

#98 Release 1 5 common files update
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/S

#99 Update deps to latest patch versions
  go.mod
  go.sum
  licenses/github.com/OneOfOne/xxhash/LICENSE
  licenses/github.com/cespare/xxhash/LICENSE.txt
  licenses/github.com/json-iterator/go/LICENSE
  licenses/github.com/modern-go/concurrent/LICENSE
  licenses/github.com/modern-go/reflect2/LICENSE
Labels: cla: yes, size/L

#100 Automator: update common-files@master in istio/pkg@master
  LICENSE
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#102 Release 1.5 codeowners + master references
  CODEOWNERS
  LICENSE
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#103 fix race between ExportMetrics and ExportView
  collateral/metrics/opencensus.go
Labels: cherrypick/release-1.5, cla: yes, size/XS

#105 Update common file to 1.5 branch
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#101 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/lint_go.sh
Labels: cla: yes, size/M
