Repository istio/pkg, pull requests merged in 2020-02, with the labels that each got.

#104 [release-1.5] fix race between ExportMetrics and ExportView
  collateral/metrics/opencensus.go
Labels: cla: yes, size/XS

#106 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#107 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#97 Add probe cobra command
  probe/cobra.go
  probe/cobra_test.go
  probe/option.go
  probe/option_test.go
Labels: cla: yes, ok-to-test, size/L

#108 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#109 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#110 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#113 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#114 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS
