Repository istio/pkg, pull requests merged in 2020-04, with the labels that each got.

#132 Automator: update common-files@master in istio/pkg@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#133 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#134 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#135 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#136 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#138 Fix lint errors for golangci-lint 1.24
  attribute/finder_test.go
Labels: cla: yes, size/XS

#137 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#139 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#140 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#141 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#143 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#144 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#145 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#146 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#148 Add codeowners for release 1.6 managers
  CODEOWNERS
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#142 Add hook to record method in monitoring pkg
  monitoring/monitoring.go
  monitoring/monitoring_test.go
Labels: cla: yes, size/L

#149 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#150 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
