Repository istio/pkg, pull requests merged in 2021-11, with the labels that each got.

#428 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#429 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#430 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#433 [release-1.12] Change CODEOWNERS in 1.12 branch
  CODEOWNERS
Labels: cla: yes, size/XS

#432 Revert changes to CODEOWNERS back to T&R
  CODEOWNERS
Labels: cla: yes, size/XS

#431 Update yaml library to use sigs.k8s.io/yaml
  go.mod
  go.sum
  licenses/sigs.k8s.io/yaml/LICENSE
  version/cobra.go
  version/cobra_test.go
Labels: cla: yes, size/XS

#434 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#435 Automator: update common-files@release-1.11 in istio/pkg@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#436 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#437 Update common-files to master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.hadolint.yml
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: cla: yes, size/M
