Repository istio/pkg, pull requests merged in 2021-04, with the labels that each got.

#331 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#332 [release-1.10] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#333 Automator: update common-files@release-1.10 in istio/pkg@release-1.10
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#334 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#335 Automator: update common-files@release-1.10 in istio/pkg@release-1.10
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#337 Automator: update common-files@release-1.8 in istio/pkg@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#336 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#338 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#339 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#340 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#342 Protect klog configuration from race conditions
  log/config.go
Labels: cla: yes, size/S

#343 Automator: update common-files@release-1.10 in istio/pkg@release-1.10
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#344 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#345 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
