Repository istio/pkg, pull requests merged in 2021-06, with the labels that each got.

#366 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#367 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#369 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#370 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#360 [release-1.10] Add support for int64 measures
  monitoring/monitoring.go
  monitoring/monitoring_test.go
Labels: cla: yes, release-notes-none, size/L

#371 Automator: update common-files@release-1.10 in istio/pkg@release-1.10
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#372 fix redundant parenteses
  log/stackdriver.go
Labels: cla: yes, ok-to-test, size/XS

#375 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#376 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#374 Export NewLogrAdapter
  log/config.go
  log/logr.go
  log/logr_test.go
Labels: cla: yes, size/XS

#377 add support for quota project to teeToStackdriver
  go.mod
  log/config.go
  log/options.go
  log/stackdriver.go
Labels: cla: yes, size/M

#378 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#373 Add log tee to a UDS server.
  log/config.go
  log/options.go
  log/uds.go
  log/uds_test.go
Labels: cla: yes, size/L

#379 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
