Repository istio/pkg, pull requests merged in 2021-12, with the labels that each got.

#439 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#438 Trim modules provided by package
  attribute/bag.go
  attribute/bag_test.go
  attribute/doc.go
  attribute/emptyBag.go
  attribute/expression.go
  attribute/list.go
  attribute/list_test.go
  attribute/mutableBag.go
  attribute/reference.go
  attribute/stringmap.go
  attribute/stringmap_test.go
  collateral/control.go
  go.mod
  go.sum
  licenses/github.com/davecgh/go-spew/LICENSE
  licenses/github.com/golang/glog/LICENSE
  licenses/github.com/hashicorp/errwrap/LICENSE
  licenses/github.com/hashicorp/go-multierror/LICENSE
  licenses/github.com/hashicorp/hcl/LICENSE
  licenses/github.com/magiconair/properties/LICENSE
  licenses/github.com/mitchellh/mapstructure/LICENSE
  licenses/github.com/pelletier/go-toml/LICENSE
  licenses/github.com/pmezard/go-difflib/LICENSE
  licenses/github.com/spf13/afero/LICENSE.txt
  licenses/github.com/spf13/cast/LICENSE
  licenses/github.com/spf13/jwalterweatherman/LICENSE
  licenses/github.com/spf13/viper/LICENSE
  licenses/github.com/stretchr/testify/LICENSE
  licenses/gopkg.in/yaml.v3/LICENSE
  log/config_test.go
  pool/buffer.go
  pool/buffer_test.go
  pool/goroutine.go
  pool/goroutine_test.go
  pool/intern.go
  pool/intern_test.go
  probe/client.go
  probe/client_test.go
  probe/cobra.go
  probe/cobra_test.go
  probe/controller.go
  probe/controller_test.go
  probe/option.go
  probe/option_test.go
  probe/probe.go
  probe/probe_test.go
  timedfn/withtimeout.go
  timedfn/withtimeout_test.go
  viperconfig/testconfig.yaml
  viperconfig/testlistconfig.yaml
  viperconfig/testsubconfig.yaml
  viperconfig/viperconfig.go
  viperconfig/viperconfig_test.go
Labels: cla: yes, size/XXL

#440 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#441 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#442 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#443 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#444 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#445 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#446 Fix use of klog/v2 to use logr.Logger struct instead of interface
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/pkg.iml
  .idea/vcs.xml
  go.mod
  go.sum
  log/logr.go
Labels: size/M

#447 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#448 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
