Repository istio/pkg, pull requests merged in 2021-02, with the labels that each got.

#314 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#316 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#317 Automator: update common-files@release-1.8 in istio/pkg@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#318 Add experimental support for Stackdriver logging to log package
  go.mod
  go.sum
  licenses/cloud.google.com/go/LICENSE
  licenses/cloud.google.com/go/logging/LICENSE
  licenses/cloud.google.com/go/third_party/pkgsite/LICENSE
  licenses/github.com/golang/groupcache/LICENSE
  licenses/github.com/googleapis/gax-go/v2/LICENSE
  licenses/github.com/stretchr/testify/LICENSE
  licenses/golang.org/x/oauth2/LICENSE
  licenses/google.golang.org/api/LICENSE
  licenses/google.golang.org/api/internal/third_party/uritemplates/LICENSE
  licenses/google.golang.org/genproto/LICENSE
  licenses/google.golang.org/protobuf/LICENSE
  licenses/gopkg.in/yaml.v3/LICENSE
  log/config.go
  log/options.go
  log/stackdriver.go
Labels: cla: yes, size/XXL

#319 Update make gen to also format go files. Run gofumpt.
  Makefile.core.mk
  attribute/emptyBag.go
  cache/cache_test.go
  collateral/metrics/opencensus_test.go
  cover/blockstate.go
  cover/ctrlz.go
  cover/registry_test.go
  ctrlz/ctrlz.go
  ctrlz/topics/collection.go
  ctrlz/topics/env.go
  env/var.go
  env/var_test.go
  ledger/ledger_test.go
  ledger/node.go
  ledger/smt.go
  ledger/smt_test.go
  ledger/util.go
  log/config_test.go
  log/default_test.go
  log/options.go
  log/scope.go
  monitoring/example_gauge_test.go
  monitoring/monitoring_test.go
  timedfn/withtimeout_test.go
  version/cobra.go
  version/version_linux_test.go
  version/version_test.go
  viperconfig/viperconfig.go
  viperconfig/viperconfig_test.go
Labels: cla: yes, size/L

#315 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#320 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#321 Update dependencies
  ctrlz/topics/args.go
  ctrlz/topics/env.go
  ctrlz/topics/mem.go
  ctrlz/topics/metrics.go
  ctrlz/topics/proc.go
  ctrlz/topics/scopes.go
  ctrlz/topics/signals.go
  ctrlz/topics/version.go
  go.mod
  go.sum
  licenses/github.com/cespare/xxhash/v2/LICENSE.txt
  licenses/github.com/cpuguy83/go-md2man/v2/LICENSE.md
  licenses/github.com/fsnotify/fsnotify/LICENSE
  licenses/github.com/prometheus/client_model/ruby/LICENSE
  licenses/github.com/russross/blackfriday/v2/LICENSE.txt
  licenses/github.com/shurcooL/sanitized_anchor_name/LICENSE
Labels: cla: yes, size/XL

#322 Revert "Refactor Ledger for readability, allow erasing history (#278)"
  go.mod
  ledger/README.md
  ledger/diagram.svg
  ledger/gcledger.go
  ledger/gcledger_test.go
  ledger/history.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/node.go
  ledger/smt.go
  ledger/smt_test.go
  ledger/smt_tools.go
  ledger/trie_cache.go
  ledger/util.go
Labels: cla: yes, size/XXL

#323 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#324 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
