Repository istio/pkg, pull requests merged in 2021-01, with the labels that each got.

#288 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#289 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#290 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#278 Refactor Ledger for readability, allow erasing history
  go.mod
  ledger/README.md
  ledger/diagram.svg
  ledger/gcledger.go
  ledger/gcledger_test.go
  ledger/history.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/node.go
  ledger/smt.go
  ledger/smt_test.go
  ledger/smt_tools.go
  ledger/trie_cache.go
  ledger/util.go
  viperconfig/viperconfig.go
Labels: cla: yes, size/XXL

#291 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#292 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#294 common-file update along with allowing beta golang versions
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.sum
  version/cobra_test.go
Labels: cla: yes, size/M

#295 Update dependencies
  attribute/finder.go
  attribute/finder_test.go
  go.mod
  go.sum
  licenses/github.com/gogo/protobuf/LICENSE
  licenses/istio.io/api/LICENSE
Labels: cla: yes, size/XL

#296 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#297 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#298 Set release managers as CODEOWNERS for release-1.9
  CODEOWNERS
Labels: cla: yes, size/XS

#299 Use release-1.9 branch, not master
  common/Makefile.common.mk
Labels: cla: yes

#300 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#301 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#302 Another make update (this time reuslting in correct UPDATE_BRANCH)
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#303 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#304 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#305 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#306 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#307 Automator: update common-files@master in istio/pkg@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#308 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#309 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#310 Automator: update common-files@release-1.8 in istio/pkg@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#311 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#312 Automator: update common-files@release-1.7 in istio/pkg@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#313 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
