Repository istio/pkg, pull requests merged in 2021-07, with the labels that each got.

#380 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#381 Automator: update common-files@release-1.10 in istio/pkg@release-1.10
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#382 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#383 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#384 Add lock on operations to UDS log buffer.
  log/uds.go
Labels: cla: yes, size/S

#385 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#386 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#387 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#388 Automator: update common-files@release-1.9 in istio/pkg@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#389 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#390 Automator: update common-files@release-1.10 in istio/pkg@release-1.10
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#391 [release-1.11] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#392 Automator: update common-files@release-1.11 in istio/pkg@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#393 fix misspelling
  monitoring/monitoring.go
  monitoring/monitoring_test.go
Labels: cla: yes, ok-to-test, size/XS

#394 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#395 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#396 Automator: update common-files@release-1.10 in istio/pkg@release-1.10
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#397 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#398 Port vklog flag from istio/istio to pkg/log
  log/config.go
  log/klog.go
Labels: cla: yes, size/M

#399 Update common files
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#400 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#401 Add support for Close to logging package
  log/config.go
  log/stackdriver.go
Labels: cla: yes, size/M
