Repository istio/pkg, pull requests merged in 2022-02, with the labels that each got.

#473 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#475 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#477 [release-1.13] Fix linting errors with new common-files update
  ctrlz/fw/context.go
  ctrlz/topics/env.go
  filewatcher/filewatcher.go
  filewatcher/filewatcher_test.go
  log/config.go
  version/stats.go
Labels: size/M, release-notes-none

#476 Automator: update common-files@release-1.13 in istio/pkg@release-1.13
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#478 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#479 [release-1.13] Fix common files
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/S

#480 Fix uds log error return check.
  log/config.go
Labels: size/XS

#481 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#482 Automator: update common-files@release-1.11 in istio/pkg@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#484 update comment
  monitoring/monitoring.go
Labels: size/XS

#485 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#486 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#488 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#489 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
