Repository istio/pkg, pull requests merged in 2022-05, with the labels that each got.

#545 Automator: update common-files@master in istio/pkg@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#548 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#549 Automator: update common-files@release-1.14 in istio/pkg@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#550 Automator: update common-files@release-1.13 in istio/pkg@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#551 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#552 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#553 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#554 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#555 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#557 Manual common-files update with lint fixes
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  cover/blockstate.go
  cover/registry.go
  cover/registry_test.go
  ledger/smt.go
  log/options.go
  log/scope.go
  log/zapcore_handler.go
Labels: size/M

#556 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/XS, auto-merge, release-notes-none

#558 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#559 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#560 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#546 [release-1.12] fix unknown scope
  log/config.go
  log/config_test.go
Labels: size/S, release-notes-none
