Repository istio/pkg, pull requests merged in 2022-03, with the labels that each got.

#490 Add basic label support for derived metrics
  monitoring/monitoring.go
  monitoring/monitoring_test.go
Labels: size/L

#492 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#494 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#495 Automator: update common-files@release-1.13 in istio/pkg@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#496 Automator: update common-files@release-1.12 in istio/pkg@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#497 Automator: update common-files@release-1.11 in istio/pkg@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#498 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#499 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#500 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#501 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#502 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#503 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#504 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#505 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#506 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/L, auto-merge, release-notes-none

#508 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#510 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#511 Update dependecies
  go.mod
  go.sum
  licenses/cloud.google.com/go/compute/LICENSE
  licenses/github.com/shurcooL/sanitized_anchor_name/LICENSE
  licenses/go.uber.org/multierr/LICENSE.txt
Labels: size/L

#512 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#513 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#514 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#515 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#516 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#517 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#518 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
