Repository istio/pkg, pull requests merged in 2022-10, with the labels that each got.

#638 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#639 Automator: update common-files@release-1.14 in istio/pkg@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#640 Automator: update common-files@release-1.15 in istio/pkg@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#642 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#643 Add build arch to build info
  version/version.go
Labels: size/S

#645 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#646 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#647 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#648 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#649 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#650 Add buildOS to build info
  version/version.go
Labels: size/XS

#651 [release-1.16] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#652 Automator: update common-files@release-1.16 in istio/pkg@release-1.16
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#653 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#654 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#655 Automator: update common-files@release-1.16 in istio/pkg@release-1.16
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#656 Manual update-common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/report_build_info.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS

#657 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#658 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/XS, auto-merge, release-notes-none

#659 Update dependencies
  go.mod
  go.sum
  licenses/github.com/fsnotify/fsnotify/LICENSE
Labels: size/L

#660 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#661 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#662 Automator: update common-files@release-1.16 in istio/pkg@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#663 chore(deps): use modules instead of incompatible
  go.mod
  go.sum
  ledger/ledger_test.go
  ledger/smt_test.go
  licenses/github.com/pkg/errors/LICENSE
  licenses/gopkg.in/natefinch/lumberjack.v2/LICENSE
  licenses/gotest.tools/v3/LICENSE
  licenses/gotest.tools/v3/internal/difflib/LICENSE
  log/config.go
Labels: size/M, ok-to-test
