Repository istio/pkg, pull requests merged in 2022-08, with the labels that each got.

#594 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#595 Automator: update common-files@release-1.14 in istio/pkg@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#596 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#597 Automator: update common-files@release-1.14 in istio/pkg@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#598 [release-1.15] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#600 Automator: update common-files@release-1.15 in istio/pkg@release-1.15
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#601 [release-1.15] Update common files from release-1.15 branch
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS

#603 Updates for new linter
  filewatcher/fakefilewatcher_test.go
Labels: size/XS

#602 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#604 Automator: update common-files@release-1.15 in istio/pkg@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#606 Updates to fix lint and gen with Go 1.19
  appsignals/watcher_test.go
  cache/cache.go
  cover/ctrlz_test.go
  ctrlz/assets/assets.gen.go
  filewatcher/filewatcher_test.go
  log/config.go
  log/config_test.go
  log/scope.go
  log/uds_test.go
  monitoring/example_distribution_test.go
  version/version.go
Labels: size/L

#605 Enable configuring klog without cobra
  appsignals/watcher_test.go
  cache/cache.go
  cover/ctrlz_test.go
  ctrlz/assets/assets.gen.go
  filewatcher/filewatcher_test.go
  log/config.go
  log/config_test.go
  log/klog.go
  log/scope.go
  log/uds_test.go
  monitoring/example_distribution_test.go
  version/version.go
Labels: size/L

#608 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#609 Automator: update common-files@release-1.14 in istio/pkg@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#610 Automator: update common-files@release-1.15 in istio/pkg@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#611 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#612 Automator: update common-files@release-1.15 in istio/pkg@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#614 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#613 env: support generic env vars
  collateral/control.go
  env/var.go
  env/var_test.go
  go.mod
  go.sum
  licenses/github.com/googleapis/enterprise-certificate-proxy/LICENSE
  licenses/gopkg.in/yaml.v3/LICENSE
Labels: size/XL

#616 Fix deprecated setoutput
  version/cobra_test.go
Labels: size/XS

#617 log: drop deprecated log types
  log/default.go
  log/default_test.go
  log/scope.go
  log/scope_test.go
Labels: size/M

#618 Automator: update common-files@release-1.13 in istio/pkg@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#619 Add interface to store collections of env vars
  env/var.go
Labels: size/S

#620 add support for conditional registration of metrics
  monitoring/monitoring.go
  monitoring/monitoring_test.go
Labels: size/M

#622 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#623 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
