Repository istio/pkg, pull requests merged in 2023-05, with the labels that each got.

#793 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#794 Automator: update common-files@release-1.18 in istio/pkg@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#797 Remove "cover" which is obsolete
  cover/assets/assets.gen.go
  cover/assets/assets.go
  cover/assets/templates/index.html
  cover/block.go
  cover/blockstate.go
  cover/coverage.go
  cover/ctrlz.go
  cover/ctrlz_test.go
  cover/doc.go
  cover/fns.go
  cover/registry.go
  cover/registry_test.go
Labels: size/XL

#795 log: simplify API
  log/config.go
  log/config_test.go
  log/default.go
  log/default_test.go
  log/klog.go
  log/options_test.go
  log/scope.go
  log/scope_test.go
Labels: size/L

#798 Update go deps
  go.mod
  go.sum
Labels: size/L, release-notes-none

#796 cleanup: move bindata gen to embed
  ctrlz/assets/assets.gen.go
  ctrlz/assets/assets.go
  ctrlz/ctrlz.go
  ctrlz/home.go
  ctrlz/topics/args.go
  ctrlz/topics/assets/assets.gen.go
  ctrlz/topics/assets/assets.go
  ctrlz/topics/collection.go
  ctrlz/topics/env.go
  ctrlz/topics/mem.go
  ctrlz/topics/metrics.go
  ctrlz/topics/proc.go
  ctrlz/topics/scopes.go
  ctrlz/topics/signals.go
  ctrlz/topics/version.go
Labels: size/M

#799 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#800 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#802 Automator: update common-files@release-1.17 in istio/pkg@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#803 Automator: update common-files@release-1.16 in istio/pkg@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#805 [CNCF graduation] Add security tab for Istio repos
  .github/SECURITY.md
Labels: size/XS

#806 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#807 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#808 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#809 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#810 Automator: update common-files@release-1.16 in istio/pkg@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#811 Automator: update common-files@release-1.18 in istio/pkg@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#813 tests: fix slow tests
  appsignals/watcher_test.go
  cache/cache_test.go
  filewatcher/filewatcher_test.go
  log/config_test.go
Labels: size/L, release-notes-none

#814 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#815 Automator: update common-files@master in istio/pkg@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/S, auto-merge, release-notes-none

#812 deprecation notice
  README.md
Labels: size/XS

#816 Automator: update common-files@release-1.17 in istio/pkg@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#817 Automator: update common-files@release-1.18 in istio/pkg@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#818 Automator: update common-files@release-1.16 in istio/pkg@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
